### ISSUE TITLE
SSR: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by kaanozcan** [pmndrs/react-spring#1144]
## 🐛 Bug Report

This issue happens in nodejs while doing ssr.

When I import ```Parallax ``` from ```renderprops-addons``` as shown below

```import { Parallax, ParallaxLayer } from "react-spring/renderprops-addons";```

nodejs throws the following error:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/repo/node_modules/@babel/runtime/helpers/esm/extends.js
require() of ES modules is not supported.
require() of /home/repo/node_modules/@babel/runtime/helpers/esm/extends.js from /home/repo/node_modules/react-spring/renderprops-addons.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename extends.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/repo/node_modules/@babel/runtime/helpers/esm/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1093:13)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/repo/node_modules/react-spring/renderprops-addons.js:7:32)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14) {
  code: 'ERR_REQUIRE_ESM'
}
```

I change import to cjs ```import { Parallax, ParallaxLayer } from "react-spring/renderprops-addons.cjs";``` and I start getting the same error on different file (renderprops.js:7:53)

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/repo/node_modules/@babel/runtime/helpers/esm/objectWithoutPropertiesLoose.js
require() of ES modules is not supported.
require() of /home/repo/node_modules/@babel/runtime/helpers/esm/objectWithoutPropertiesLoose.js from /home/repo/node_modules/react-spring/renderprops.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename objectWithoutPropertiesLoose.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/repo/node_modules/@babel/runtime/helpers/esm/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1093:13)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/repo/node_modules/react-spring/renderprops.js:7:53)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14) {
  code: 'ERR_REQUIRE_ESM'
}
```

my loader:

```
{
        test: /\.(js|jsx)$/,
        loader: "babel-loader",
        include: [
          path.join(__dirname, "/src"),
        ],
}
```

## Expected behavior

(A clear and concise description of what you expected to happen.)

## Link to repro (highly encouraged)

(Please provide either a [CodeSandbox demo](https://codesandbox.io) or an example GitHub repo.)

## Environment

- `react-spring` v8.0.27
- `react` v16.13.1
- `nodejs` v14.10.0

**Comment by 4dams** [comment]
Running into the same issue here, can also provide a repro-Repository

**Comment by spostad7** [comment]
same issue

**Comment by joshuaellis** [comment]
closing due to inactivity & we need a repro. please use discussions or discord if you want more help or please consider creating a PR if you want to add a feature 😄
